### ISSUE TITLE
Better image handling in developer docs

### ISSUE THREAD

**Issue by charleenfei** [centrifuge/developer.centrifuge.io#141]
We would like to support the addition of screenshots to the documentation. Currently, there are images directly embedded from urls, these should be available statically and displayed as grommet image components and allow them to assign image sizes. 

An example of what images look like now: https://deploy-preview-142--staging-centrifuge-documentation.netlify.com/tinlake/tinlake-demo/user-flow/

We should have a way to format images in markdown using some non-standard syntax. Features to support:
1) Size: full-width or specific size
2) Alignment: center full screen or inline with text left or right

**Comment by eswarasai** [comment]
@charleenfei - Just addressed this in a simplest possible way. Let me know if this resolves what you're looking for -- https://github.com/centrifuge/developer.centrifuge.io/pull/144

cc: @lucasvo

**Comment by lucasvo** [comment]
@eswarasai cool! As @charleenfei mentioned, local path support would be good to have as well. 

Could you add a section to the README documenting the custom markdown features we added? MathJax support and this custom image syntax?
