### ISSUE TITLE
transactions endpoint are deprecated but still in docs

### ISSUE THREAD

**Issue by Remi-Tuy** [centrifuge/developer.centrifuge.io#87]
with the latest release, `transactions` are now called `jobs`

https://centrifuge-os-node-api-1.api-docs.io/0.0.3-alpha4/transactions/8pZTEvT5XWYsMuGWa

this reference to an API point that does not exist, it should instead be `/jobs/{job_id}`

**Comment by vedhavyas** [comment]
api-docs needs to be updated with the latest version 0.0.5

**Comment by mikiquantum** [comment]
fixed by: https://github.com/centrifuge/developer.centrifuge.io/pull/104/files
